wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712192934.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
dropout:
  desc: null
  value: 0.24022807689665587
epoch:
  desc: null
  value: 3
gamma:
  desc: null
  value: 0.9521794785944656
lr:
  desc: null
  value: 0.0006088126981939869
