wandb_version: 1

dropout:
  desc: null
  value: 0.1877397430344046
epoch:
  desc: null
  value: 4
gamma:
  desc: null
  value: 0.9865237150288334
lr:
  desc: null
  value: 0.0005572473602051692
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712187178.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
