wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712192323.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
dropout:
  desc: null
  value: 0.2192918813450332
epoch:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.953692984688874
lr:
  desc: null
  value: 0.0006014179009913657
