wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712191941.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
dropout:
  desc: null
  value: 0.12122281508832938
epoch:
  desc: null
  value: 4
gamma:
  desc: null
  value: 0.9799417785475136
lr:
  desc: null
  value: 0.0007172735761503677
